### ISSUE TITLE
Fluid level card error with type gauge (at system start)

### ISSUE THREAD

**Issue by AlainPeccable** [swingerman/lovelace-fluid-level-background-card#291]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
0.1.3

**Last working release (if known):**
Unknown

**Browser and Operating System:**
Windows 11 & Google Chrome

**Description of problem:**

After restart of HA one card including Gauges is displaying an error for the one using the Fluid Level background card. All other Gauge card are working fine.  Editing the card (no need to save) resolves the issue until the next reboot of HA.

Error message:
![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/132245586/fe394137-402a-476e-b5ad-b215956cb806)

In the below example all gauges are working fine except the last one which is embedded in Fluid Level:
type: vertical-stack
cards:
  - type: glance
    show_name: true
    show_icon: true
    show_state: false
    entities:
      - entity: binary_sensor.abri_citernes_grundfos
      - entity: binary_sensor.abri_citernes_pompe
      - entity: binary_sensor.citerne_niveau_haut
      - entity: binary_sensor.citerne_vide
    title: Citerne
    columns: 4
  - type: markdown
    content: |-
      **Text explaining the values**
  - type: horizontal-stack
    cards:
      - type: gauge
        entity: sensor.abri_citernes_adc
        name: ''
        max: 6
        needle: true
        severity:
          green: 2
          yellow: 1
          red: 0
      - type: gauge
        name: ''
        entity: sensor.citerne_mazout
        max: 100
        needle: true
        severity:
          green: 25
          yellow: 15
          red: 0
      - type: gauge
        name: ''
        entity: sensor.citerne_mazout_cm
        max: 180
        needle: true
        severity:
          green: 25
          yellow: 15
          red: 0
  - type: custom:fluid-level-background-card
    entity: sensor.citerne_mazout
    level_color:
      - 128
      - 19
      - 0
    card:
      type: gauge
      entity: sensor.citerne_mazout_l
      max: 3000
      needle: true
      severity:
        green: 800
        yellow: 400
        red: 0
      min: 0
      unit: L

**Comment by MrTheoW** [comment]
I have the same issue. But when I edit the card and turn the needle off/on it works again.

**Comment by DM-AU** [comment]
I have the same issue.

**Comment by ildar170975** [comment]
@AlainPeccable 
1. What you posted is unformatted code which in general cannot be properly analysed.
2. Posting an unrelated code distracts people from the issue. You posted 6 cards and only 1 card is related. Google "Minimal working example".

Here is a minimal test code:
```
type: custom:fluid-level-background-card
card:
  type: gauge
  entity: input_number.test_level_1
entity: input_number.test_level_1
```
![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/febdfea0-7372-4f58-97c9-4765f55d4859)

**Comment by AlainPeccable** [comment]
Hello,
This is from last year and in the meantime there has been a new release with which I don't have the issue anymore. The issue was not with the formatting as a simple edit without saving solved the issue after each restart of HA.

for me this is closed.

**Comment by ildar170975** [comment]
No, the issue still there:
![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/8096a3bf-2e4d-457f-bc16-72f32540a1a3)
And similar things may happen with other cards, like "card inside a custom field in custom:button-card".

**Comment by DM-AU** [comment]
> No, the issue still there: ![image](https://private-user-images.githubusercontent.com/71872483/324176720-8096a3bf-2e4d-457f-bc16-72f32540a1a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTYwNDQsIm5iZiI6MTcxMzYxNTc0NCwicGF0aCI6Ii83MTg3MjQ4My8zMjQxNzY3MjAtODA5NmEzYmYtMmU0ZC00NTdmLWJjMTYtNzJmMzI1NDBhMWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEyMjIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNDkxMjQ5OGY2M2ZmOTY0OTBjNzY0NjZlNzg4ZDhhYTg2YTJmZjU1MzY4YmZlNzc5MjZjMjU2ZmU1Njc2Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZxJKXb4U2V_MVc0b8FmbVU4ZpHCaeBzdTTzIMR3vLao) And similar things may happen with other cards, like "card inside a custom field in custom:button-card".

Agreed. Absolutely not resolved and can easily replicate the issue exactly as described in original post.

`type: custom:fluid-level-background-card
card:
  type: gauge
  entity: sensor.water_tank_percent
  needle: true
  severity:
    green: 50
    yellow: 15
    red: 0
entity: sensor.water_tank_percent
level_color:
  - 51
  - 177
  - 255`

**Comment by AlainPeccable** [comment]
I created a new card just to test and indeed it still not work.

I'm not using the card as I was using it last year and I'm not having any issues anymore, all my cards are part of the "custom:stack-in-card"

If I simulate the same with the standard horizontal or vertical stack I also don't see the issue.

`
type: horizontal-stack
cards:
  - type: custom:fluid-level-background-card
    card:
      type: gauge
      entity: sensor_water_tank_percent
      needle: true
      severity:
        green: 50
        yellow: 15
        red: 0
    entity: sensor_water_tank_percent
    level_color:
      - 51
      - 177
      - 255
`

So yes there is still an issue but also a workaround.

**Comment by AlainPeccable** [comment]
I created a new card just to test and indeed it still not work. Now I'm not using the card as I was using them last year all my cards are part of the "custom:stack-in-card"

If I simulate the same with the standard horizontal or vertical stack I also don't see the issue.

`
type: horizontal-stack
cards:
  - type: custom:fluid-level-background-card
    card:
      type: gauge
      entity: sensor_water_tank_percent
      needle: true
      severity:
        green: 50
        yellow: 15
        red: 0
    entity: sensor_water_tank_percent
    level_color:
      - 51
      - 177
      - 255
`

**Comment by swingerman** [comment]
Yes it brakes. Looked into it on Friday but wasn't able to fix it. Please stay tuned.

**Comment by swingerman** [comment]
I think it should be fixed. I will publish a new beta today.

**Comment by swingerman** [comment]
Please check [v0.1.6-beta.5](https://github.com/swingerman/lovelace-fluid-level-background-card/releases/tag/v0.1.6-beta.5)

**Comment by AlainPeccable** [comment]
Tested with the test card created 2 weeks ago and working for me. And all my existing dashboards looks also ok.

**Comment by ildar170975** [comment]
With the latest release, I do not see the "custom element does not exist" error.
But the whole card may be not displayed:
```
type: custom:fluid-level-background-card
card:
  type: gauge
  entity: input_number.test_level_1
entity: input_number.test_level_1
```
A sequence:
1. Create a new card, paste this code.
2. The card is shown in Editor:
![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/a724149d-26da-489b-9b8b-71f9f6c28e04)
3. Save the card & cLose the Editor.
4. The card is still shown:
![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/65da126c-adc2-4d54-b737-585988945c83)
5. Refresh a page (F5 in Chrome).
6. The card is not shown:
![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/a47bcf98-aafa-4531-a4c3-ee018fc18789)
7. How to fix: open the card in Editor & close the Editor -> the card is shown again (until you press F5).

A similar in yaml-mode dashboard:
1. After F5 the card is not shown.
2. How to fix: select "Refresh" from a HA menu -> the card is shown again (until you press F5).

Not sure if I should create a new issue.
With another card I do not see the problem:
```
type: custom:fluid-level-background-card
card:
  type: entity
  entity: input_number.test_level_1
entity: input_number.test_level_1
```

**Comment by DM-AU** [comment]
I am still having issues. If I refresh enough the card will load or if I just choose to edit the card it will render, however I also have 2 errors which appear and change when I refresh:

Error 1:
![error 1](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/66342521/f819c0a1-4b3d-46f6-93e7-508019738e11)

Error 2:
![error 2](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/66342521/03bd2284-e08a-4d62-9929-b9c627f30c3b)

```
type: custom:fluid-level-background-card
card:
  type: gauge
  entity: sensor.water_tank_percent
  needle: true
  severity:
    green: 50
    yellow: 15
    red: 0
  name: House
entity: sensor.water_tank_percent
level_color:
  - 61
  - 180
  - 240
tap_action:
  action: more-info
```

**Comment by ildar170975** [comment]
@DM-AU have you cleared a browser's cache?

**Comment by DM-AU** [comment]
> @DM-AU have you cleared a browser's cache? Any chance you are still using a prev version?

Sorry, you were right I didnt update (i had selected the beta version in HACS but didnt update). 

Status: No more errors. However I have the same issue as ildar170975 where the card is now completely invisible. The only way to bring it to view is to edit the card which renders it.

**Comment by swingerman** [comment]
Please check [v0.1.6-beta.6](https://github.com/swingerman/lovelace-fluid-level-background-card/releases/tag/v0.1.6-beta.6)

**Comment by ildar170975** [comment]
Tested after update:
Two cards in "storage mode" dashboard:
```
type: custom:fluid-level-background-card
card:
  type: entity
  entity: input_number.test_level_1
entity: input_number.test_level_1
```
```
type: custom:fluid-level-background-card
card:
  type: gauge
  entity: input_number.test_level_1
entity: input_number.test_level_1
```
Usually are shown as
![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/26a30e71-8ba7-47f4-aeb5-c6ccc5d3bba2)

But sometimes after F5 (~25% cases):
![image](https://github.com/swingerman/lovelace-fluid-level-background-card/assets/71872483/d5c1ec66-e38f-4280-93ef-a1d2d6d7f029)

I see a similar behaviour with many custom cards.
I.e. could be not a fluid-card issue...

**Comment by DM-AU** [comment]
I have tested on an iPad, and 2x Windows computers using Edge and it is now displaying/working correctly. I will monitor and update if any changes. Thankyou for resolving!
